[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "microscope-calibration"
description = "Tools to calibrate a microscope"
license = {file = "LICENSE"}
keywords = ["microscopy", "LiberTEM", "TEM", "STEM"]
requires-python = ">=3.14"
dynamic = ["version", "readme"]
# Stripped down to only support model.py
# TODO strategy on how to integrate with other SW without pulling in
# all scientific Python packages
dependencies = [
    "jax",
    "jax-dataclasses",
    # FIXME change to release TemGymCore when possible
    "temgym-core@git+https://github.com/TemGym/TemGymCore.git",
    "sympy",
    "wrapt",
    "frozendict",
    "flax",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 3 - Alpha",
]
authors = [
    {name="Dieter Weber", email="d.weber@fz-juelich.de"},
]

[project.urls]
repository = "https://github.com/LiberTEM/Microscope-Calibration"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
common = [
    "libertem",
    # Minimum constraints of numba for all Python versions we support
    # See https://numba.readthedocs.io/en/stable/release-notes-overview.html
    "numba>=0.55;python_version < '3.11'",
    "numba>=0.57;python_version < '3.12'",
    "numba>=0.59;python_version < '3.13'",
    # for any future Python release, constrain numba to a recent version,
    # otherwise, version resolution might try to install an ancient version
    # that isn't constrained properly:
    "numba>=0.61;python_version >= '3.13'",
    "scipy",
    "scikit-image",
    "optax",
    "optimistix",
    "numpy",
]
diffraction = [
    "pycifrw",
    "diffpy.structure",
    "orix",
    # Until https://github.com/pyxem/diffsims/pull/245/ is released
    "diffsims@git+https://github.com/pyxem/diffsims"
]
gui = [
    "libertem-blobfinder",
    # FIXME change to release LiberTEM-panel-ui when possible
    "libertem-ui@git+https://github.com/matbryan52/LiberTEM-panel-ui",
    "ipywidgets", "pandas", "panel", "bokeh", "sparse"
    # Also requires diffraction, TODO how to handle?
]

[tool.setuptools.dynamic]
version = {attr = "microscope_calibration.__version__"}
readme = {file = ["README.md"], content-type="text/markdown"}

[tool.ruff]

line-length = 100
extend-exclude = ["prototypes"]
force-exclude = true

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore = ["E24", "E226", "E241", "E242", "B007"]
