[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
  "src/microscope_calibration",
]
only-packages = true

[tool.hatch.build.targets.sdist]
include = [
  "src/microscope_calibration",
  "tests",
  "CITATION.cff",
  "pytest.ini",
  "setup.cfg",
]

# Version is derived from git tags like v0.1.0
[tool.hatch.version]
source = "vcs"

# FIXME remove when the git URL dependencies in the extras are released
[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "microscope-calibration"
description = "Tools to calibrate a microscope"
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
keywords = ["microscopy", "LiberTEM", "TEM", "STEM"]
requires-python = ">=3.14"
dynamic = ["version"]
# Stripped down to only support model.py
# TODO strategy on how to integrate with other SW without pulling in
# all scientific Python packages
dependencies = [
    "jax",
    "jax-dataclasses",
    "temgym-core",
    "sympy",
    "wrapt",
    "frozendict",
    "flax",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 3 - Alpha",
]
authors = [
    {name="Dieter Weber", email="d.weber@fz-juelich.de"},
    {name="David Landers", email="davidlandersresearch@gmail.com"},
    {name="Margarita Usoltceva", email="margousol@gmail.com"},
    {name="Matthew Bryan", email="matthewbryan52@gmail.com"},
    {name="Alexander Clausen", email="a.clausen@fz-juelich.de"},
]

[project.urls]
repository = "https://github.com/LiberTEM/Microscope-Calibration"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
common = [
    "libertem",
    # Minimum constraints of numba for all Python versions we support
    # See https://numba.readthedocs.io/en/stable/release-notes-overview.html
    "numba>=0.55;python_version < '3.11'",
    "numba>=0.57;python_version < '3.12'",
    "numba>=0.59;python_version < '3.13'",
    # for any future Python release, constrain numba to a recent version,
    # otherwise, version resolution might try to install an ancient version
    # that isn't constrained properly:
    "numba>=0.61;python_version >= '3.13'",
    "scipy",
    "scikit-image",
    "optax",
    "optimistix",
    "numpy",
]
diffraction = [
    "pycifrw",
    "diffpy.structure",
    "orix",
    # Until https://github.com/pyxem/diffsims/pull/245/ is released
    "diffsims@git+https://github.com/pyxem/diffsims"
]
gui = [
    "libertem-blobfinder",
    # FIXME change to release LiberTEM-panel-ui when possible
    "libertem-ui@git+https://github.com/LiberTEM/LiberTEM-panel-ui",
    "ipywidgets", "pandas", "panel", "bokeh", "sparse",
    # for util.jeol_dm4
    "pint", "ncempy",
    # Also requires diffraction, TODO how to handle?
]

[tool.ruff]

line-length = 100
extend-exclude = ["prototypes"]
force-exclude = true

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore = ["E24", "E226", "E241", "E242", "B007"]
