[pytest]
norecursedirs = .git .tox *.egg-info build node_modules TOXENV prototypes .ipynb_checkpoints
addopts = --strict-markers
markers =
    with_numba: mark tests that exercise a numba function so we can re-run for coverage
log_level=INFO
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
