name: CI

on:
  push:
    branches:
      - master
      - 'v[0-9]*'
    tags:
      - 'v[0-9]*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-14]
        exclude:
          - os: macos-14
            python_version: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Choose Python version ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python_version }}'
      - name: install the package
        run: python3 -m pip install .[test]
      - name: run pytest
        run: pytest --cov=microscope_calibration --cov-report=xml --cov-report=term tests/
      - name: submit code coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  numba_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Choose Python version 3.12'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install the package
        run: python3 -m pip install .[test]
      - name: run pytest
        run: NUMBA_DISABLE_JIT=1 pytest --cov=microscope_calibration --cov-report=xml --cov-report=term tests/
      - name: submit code coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
